### ISSUE TITLE
todo section

### ISSUE THREAD

**Issue by Xayrulloh** [planit-org/planit#9]
- [x] create todo
- [x] update todo
- [x] delete todo
- [x] get by id todo
- [x] get all todo

**Comment by Xayrulloh** [comment]
- [ ] create list (text, image optional)
- [ ] update list
- [ ] delete list
